package org.example.service;

import org.example.entity.PersonalHaul;
import org.example.repository.PersonalHaulRepository;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Business logic for personal haul entries.
 *
 * <p>Uses raw JDBC for inserts because the primary key ({@code entry_time}) is
 * auto-generated by the database via {@code DEFAULT now()}, which JPA cannot
 * handle for identity generation. After inserting, fetches the most recent
 * row to return the full entity with its generated timestamp.</p>
 */
@Service
public class PersonalHaulService {

    private final PersonalHaulRepository repo;
    private final JdbcTemplate jdbc;

    public PersonalHaulService(PersonalHaulRepository repo, JdbcTemplate jdbc) {
        this.repo = repo;
        this.jdbc = jdbc;
    }

    public List<PersonalHaul> findAll() {
        return repo.findAll();
    }

    public PersonalHaul create(String flowType, BigDecimal amount, String note) {
        jdbc.update(
            "INSERT INTO personal_hauls (flow_type, amount, note) VALUES (?, ?, ?)",
            flowType, amount, note
        );
        // Return the most recently inserted row
        return jdbc.queryForObject(
            "SELECT entry_time, flow_type, amount, note FROM personal_hauls ORDER BY entry_time DESC LIMIT 1",
            (rs, rowNum) -> {
                PersonalHaul h = new PersonalHaul();
                h.setEntryTime(rs.getObject("entry_time", OffsetDateTime.class));
                h.setFlowType(rs.getString("flow_type"));
                h.setAmount(rs.getBigDecimal("amount"));
                h.setNote(rs.getString("note"));
                return h;
            }
        );
    }

    public void delete(OffsetDateTime entryTime) {
        repo.deleteById(entryTime);
    }
}
